portfolio_site/blog/urls.py
from django.urls import path
from .views import LikePostView, PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('post-create/', PostCreateView.as_view(), name='post-create'),
    path('post-update/<slug:slug>/', PostUpdateView.as_view(), name='post-update'),
    path('post-delete/<slug:slug>/', PostDeleteView.as_view(), name='post-delete'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('like/<slug:slug>/', LikePostView.as_view(), name='like_post'),
]

portfolio_site/portfolio_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('users.urls')),
    path('admin/logout/', LogoutView.as_view(next_page='/'), name='admin_logout'),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio_site/users/urls.py
from django.urls import path
from .views import CustomLoginView, ProfileView, RegisterView, FollowAuthorView, UnfollowAuthorView, EditProfileView, SubscriptionCreateView, SubscriptionSuccessView
from django.contrib.auth.views import LogoutView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('follow/<int:user_id>/', FollowAuthorView.as_view(), name='follow_author'),
    path('unfollow/<int:user_id>/', UnfollowAuthorView.as_view(), name='unfollow_author'),
    path('profile/edit/', EditProfileView.as_view(), name='edit_profile'),
    path('subscribe/', SubscriptionCreateView.as_view(), name='subscribe'),
    path('subscribe/success/', SubscriptionSuccessView.as_view(), name='subscription_success'),
]

portfolio_site/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=225)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='liked_posts', blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])
    

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.post.title} ({self.created_at})"

    class Meta:
        ordering = ['-created_at']
        

portfolio_site/blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'placeholder': 'Ваш коментар'}),
        }

portfolio_site/blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import DetailView, UpdateView, DeleteView, CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Post, Comment
from .filters import PostFilter
from .forms import CommentForm
from django.utils.text import slugify
from users.models import Subscription
from django.core.paginator import Paginator


class PostListView(ListView):
    model = Post
    template_name = 'blog/post_list.html'
    context_object_name = 'posts'
    paginate_by = 7

    def get_queryset(self):
        queryset = Post.objects.all().select_related('author', 'category').prefetch_related('tags')
        self.filterset = PostFilter(self.request.GET, queryset=queryset, request=self.request)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filterset
        return context
    

class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/post_create.html'
    context_object_name = 'task'
    success_url = reverse_lazy('blog:posts')
    fields = ['title', 'content', 'category', 'tags']

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return self.handle_no_permission()
        if not Subscription.objects.filter(user=request.user, is_active=True).exists():
            return redirect('users:subscribe')  
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.title)
        return super(PostCreateView, self).form_valid(form)


class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['is_liked'] = self.request.user in self.object.likes.all()
            context['comment_form'] = CommentForm()
        context['like_count'] = self.object.likes.count()
        comments = self.object.comments.all()
        paginator = Paginator(comments, 5)  
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        return context
    
    def post(self, request, *args, **kwargs):
        post = self.get_object()
        if not request.user.is_authenticated:
            return redirect('users:login')

        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.user = request.user
            comment.save()
            return redirect(post.get_absolute_url())

        context = self.get_context_data()
        context['comment_form'] = form
        return self.render_to_response(context)


class LikePostView(LoginRequiredMixin, View):
    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        if request.user in post.likes.all():
            post.likes.remove(request.user) 
        else:
            post.likes.add(request.user) 
        return HttpResponseRedirect(reverse('blog:post_detail', args=[slug]))


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'blog/post_create.html'
    context_object_name = 'post'
    fields = ['title', 'content', 'category', 'tags']
    success_url = reverse_lazy('blog:posts')


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'
    context_object_name = 'post'
    success_url = reverse_lazy('blog:posts')

    

portfolio_site/templates/blog/post_create.html
{% extends 'shop/base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="card p-4" style="max-width: 600px; margin: 0 auto;">
        <h1>Створення посту</h1>
        <a href="{% url 'blog:posts' %}" class="btn btn-secondary mb-3">Назад</a>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <div class="text-danger">
                            {% for error in field.errors %}
                                <small>{{ error }}</small>
                            {% endfor %}
                        </div>
                    {% endif %}
                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Створити</button>
        </form>
    </div>
</div>
{% endblock %}

portfolio_site/templates/blog/post_delete.html
{% extends 'shop/base.html' %}
{% block content %}
<div class="card p-4">
    <h1>Видалення посту</h1>
    <a href="{% url 'blog:posts' %}" class="btn btn-secondary mb-3">Назад</a>
    <form method="post">
        {% csrf_token %}
        <p>Видалити пост "{{ post.title }}"?</p>
        <button type="submit" class="btn btn-primary">Видалити</button>
    </form>
</div>
{% endblock %}

portfolio_site/templates/blog/post_detail.html
{% extends 'shop/base.html' %}
{% load static thumbnail %}
{% block content %}
<div class="blog-post">
    <div class="card">
        <div class="card-body">
            <h1>{{ post.title }}</h1>
            <p>Автор: <a href="{% url 'users:profile' %}?user_id={{ post.author.id }}">{{ post.author.username }}</a></p>
            <p>Категорія: <a href="{% url 'blog:posts' %}?category={{ post.category.id }}">{{ post.category.name }}</a></p>
            <p>Теги:
                {% for tag in post.tags.all %}
                    <a href="{% url 'blog:posts' %}?tags={{ tag.id }}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
                {% empty %}
                    Немає
                {% endfor %}
            </p>
            <p>{{ post.content|linebreaks }}</p>
            <p>Опубліковано: {{ post.created_at|date:"d.m.Y H:i" }}</p>
            <p>Лайки: {{ like_count }}</p>
            {% if user.is_authenticated %}
                <form action="{% url 'blog:like_post' post.slug %}" method="get" class="d-inline">
                    <button type="submit" class="btn {% if is_liked %}btn-danger{% else %}btn-primary{% endif %}">
                        {% if is_liked %}Unlike{% else %}Like{% endif %}
                    </button>
                </form>
            {% endif %}
            {% if request.user == post.author %}
                <a href="{% url 'blog:post-update' post.slug %}" class="btn btn-primary ms-2">Редагувати</a>
                <a href="{% url 'blog:post-delete' post.slug %}" class="btn btn-primary ms-2">Видалити</a>
            {% endif %}
        </div>
    </div>

    <h3 class="mt-5">Коментарі</h3>
    {% if page_obj %}
        {% for comment in page_obj %}
            <div class="card mb-3">
                <div class="card-body d-flex">
                    {% if comment.user.userprofile.avatar %}
                        <img src="{% thumbnail comment.user.userprofile.avatar 'comment_avatar' %}" alt="Аватар {{ comment.user.username }}" class="me-3" width="50" height="50">
                    {% else %}
                        <img src="{% get_static_prefix %}images/placeholder_avatar.png" alt="No Avatar" class="me-3" width="50" height="50">
                    {% endif %}
                    <div>
                        <p class="card-text text-muted"><a href="{% url 'users:profile' %}?user_id={{ comment.user.id }}">{{ comment.user.username }}</a> | {{ comment.created_at|date:"d.m.Y H:i" }}</p>
                        <p class="card-text">{{ comment.content }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
        {% if page_obj.has_other_pages %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Попередня</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">Попередня</span>
                        </li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <li class="page-item active">
                                <span class="page-link">{{ num }}</span>
                            </li>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Наступна</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">Наступна</span>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    {% else %}
        <p>Коментарі відсутні.</p>
    {% endif %}

    {% if user.is_authenticated %}
        <h4 class="mt-4">Додати коментар</h4>
        <form method="post" class="card p-4">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit" class="btn btn-primary">Надіслати</button>
        </form>
    {% else %}
        <p><a href="{% url 'users:login' %}">Увійдіть</a>, щоб залишити коментар.</p>
    {% endif %}
</div>
{% endblock %}

portfolio_site/templates/blog/post_list.html
{% extends 'shop/base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-9">
        <h1>Блог</h1>
        {% if user.is_authenticated %}
            <a href="{% url 'blog:post-create' %}" class="btn btn-primary mb-3">Додати пост</a>
        {% endif %}
        {% for post in posts %}
            <div class="card mb-3 blog-post">
                <div class="card-body">
                    <h5 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h5>
                    <p class="card-text">Автор: <a href="{% url 'users:profile' %}?user_id={{ post.author.id }}">{{ post.author.username }}</a></p>
                    <p class="card-text">Категорія: <a href="?category={{ post.category.id }}">{{ post.category.name }}</a></p>
                    {% if post.tags.all %}
                        <p class="card-text">Теги:
                            {% for tag in post.tags.all %}
                                <a href="?tags={{ tag.id }}">{{ tag.name }}</a>{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                        </p>
                    {% endif %}
                    <p class="card-text">Лайки: {{ post.likes.count }}</p>
                </div>
            </div>
        {% empty %}
            <h2>
                {% if filter.form.followed_authors.value and user.is_authenticated %}
                    Ви не відстежуєте жодного автора.
                {% else %}
                    Пости відсутні
                {% endif %}
            </h2>
        {% endfor %}

        {% if page_obj.has_other_pages %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">Попередня</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">Попередня</span>
                        </li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        {% if page_obj.number == num %}
                            <li class="page-item active">
                                <span class="page-link">{{ num }}</span>
                            </li>
                        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ num }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">{{ num }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}{% for key, value in request.GET.items %}{% if key != 'page' %}&{{ key }}={{ value }}{% endif %}{% endfor %}">Наступна</a>
                        </li>
                    {% else %}
                        <li class="page-item disabled">
                            <span class="page-link">Наступна</span>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
    <div class="col-md-3">
        <div class="filter-section">
            <h3>Фільтрація</h3>
            <form method="get">
                <div class="mb-3">
                    <label for="{{ filter.form.title.id_for_label }}" class="form-label">{{ filter.form.title.label }}</label>
                    <input type="text" name="{{ filter.form.title.name }}" id="{{ filter.form.title.id_for_label }}" value="{{ filter.form.title.value|default_if_none:'' }}" class="form-control">
                </div>
                <div class="mb-3">
                    <label for="{{ filter.form.category.id_for_label }}" class="form-label">{{ filter.form.category.label }}</label>
                    {{ filter.form.category }}
                </div>
                <div class="mb-3">
                    <label class="form-label">{{ filter.form.tags.label }}</label>
                    {{ filter.form.tags }}
                </div>
                <div class="mb-3">
                    <label for="{{ filter.form.author.id_for_label }}" class="form-label">{{ filter.form.author.label }}</label>
                    {{ filter.form.author }}
                </div>
                {% if user.is_authenticated %}
                    <div class="mb-3">
                        <label class="form-label">{{ filter.form.followed_authors.label }}</label>
                        {{ filter.form.followed_authors }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ filter.form.sort_by_likes.id_for_label }}" class="form-label">{{ filter.form.sort_by_likes.label }}</label>
                        {{ filter.form.sort_by_likes }}
                    </div>
                    <div class="mb-3">
                        <label for="{{ filter.form.sort_by_date.id_for_label }}" class="form-label">{{ filter.form.sort_by_date.label }}</label>
                        {{ filter.form.sort_by_date }}
                    </div>
                {% endif %}
                <button type="submit" class="btn btn-primary">Застосувати</button>
                <a href="{% url 'blog:posts' %}" class="btn btn-secondary">Скинути фільтри</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}