portfolio_site/blog/urls.py
from django.urls import path
from .views import LikePostView, PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView

app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='posts'),
    path('post-create/', PostCreateView.as_view(), name='post-create'),
    path('post-update/<slug:slug>/', PostUpdateView.as_view(), name='post-update'),
    path('post-delete/<slug:slug>/', PostDeleteView.as_view(), name='post-delete'),
    path('<slug:slug>/', PostDetailView.as_view(), name='post_detail'),
    path('like/<slug:slug>/', LikePostView.as_view(), name='like_post'),
]

portfolio_site/cart/urls.py
from django.urls import path
from .views import CartView, add_to_cart, update_cart_item, remove_cart_item

app_name = 'cart'
urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('update/<int:item_id>/', update_cart_item, name='update_cart_item'),
    path('remove/<int:item_id>/', remove_cart_item, name='remove_cart_item'),
]

portfolio_site/portfolio_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('users.urls')),
    path('admin/logout/', LogoutView.as_view(next_page='/'), name='admin_logout'),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portfolio_site/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),
    path('products/', views.ProductListView.as_view(), name='product_list'),
    path('products/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('products/<slug:slug>/track/', views.TrackProductView.as_view(), name='track_product'),
]

portfolio_site/users/urls.py
from django.urls import path
from .views import CustomLoginView, ProfileView, RegisterView, FollowAuthorView, UnfollowAuthorView, EditProfileView, SubscriptionCreateView, SubscriptionSuccessView
from django.contrib.auth.views import LogoutView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('follow/<int:user_id>/', FollowAuthorView.as_view(), name='follow_author'),
    path('unfollow/<int:user_id>/', UnfollowAuthorView.as_view(), name='unfollow_author'),
    path('profile/edit/', EditProfileView.as_view(), name='edit_profile'),
    path('subscribe/', SubscriptionCreateView.as_view(), name='subscribe'),
    path('subscribe/success/', SubscriptionSuccessView.as_view(), name='subscription_success'),
]

portfolio_site/shop/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models import Avg
from easy_thumbnails.fields import ThumbnailerImageField


class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

class Genre(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True, null=True, blank=True)

    def __str__(self):
        return self.name


class Artist(models.Model):
    name = models.CharField(max_length=225)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=225)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)
    rating = models.FloatField(default=0.0)
    is_new = models.BooleanField(default=False)
    image = ThumbnailerImageField(upload_to='products/', blank=True, null=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, null=True, blank=True)
    release_year = models.PositiveIntegerField(null=True, blank=True)
    genre = models.ManyToManyField(Genre, blank=True)
    is_available = models.BooleanField(default=True)
    quantity = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.slug])

    def get_discounted_price(self):
        if self.discount:
            return round(self.price * (1 - self.discount/100), 2)
        return self.price
    
    def update_rating(self):
        avg_rating = self.reviews.aggregate(Avg('rating'))['rating__avg']
        self.rating = round(avg_rating or 0.0, 1)
        self.save()


class Review(models.Model):
    product = models.ForeignKey(Product, related_name='reviews', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField(choices=[(i, i) for i in range(1, 6)])
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.product.name} ({self.rating})"

    class Meta:
        unique_together = ('product', 'user')
        

portfolio_site/shop/forms.py
from django import forms
from .models import Review

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['rating', 'comment']
        widgets = {
            'rating': forms.Select(choices=[(i, i) for i in range(1, 6)], attrs={'class': 'form-select'}),
            'comment': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'placeholder': 'Ваш відгук'}),
        }

portfolio_site/shop/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Category, Product, Review
from .filters import ProductFilter
from .forms import ReviewForm
from django.core.paginator import Paginator
from users.models import TrackedProduct
from django.contrib.contenttypes.models import ContentType


class HomeView(TemplateView):
    template_name = 'shop/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['new_products'] = Product.objects.filter(is_new=True).exclude(category__slug='vinyl-records')[:4]
        context['new_vinyl'] = Product.objects.filter(is_new=True, category__slug='vinyl-records')[:4]
        context['discounted_products'] = Product.objects.filter(discount__isnull=False).exclude(category__slug='vinyl-records')[:4]
        context['discounted_vinyl'] = Product.objects.filter(discount__isnull=False, category__slug='vinyl-records')[:4]
        return context


class ProductListView(ListView):
    template_name = 'shop/product_list.html'
    context_object_name = 'products'
    paginate_by = 12

    def get_queryset(self):
        queryset = Product.objects.all()
        self.filterset = ProductFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filterset
        return context


class ProductDetailView(DetailView):
    template_name = 'shop/product_detail.html'
    model = Product
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reviews = self.get_object().reviews.all()
        paginator = Paginator(reviews, 5) 
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj

        if self.request.user.is_authenticated:
            existing_review = Review.objects.filter(product=self.get_object(), user=self.request.user).first()
            if existing_review:
                context['review_form'] = ReviewForm(instance=existing_review)
                context['existing_review'] = existing_review
            else:
                context['review_form'] = ReviewForm()
            context['is_tracked'] = TrackedProduct.objects.filter(
                user_profile=self.request.user.userprofile,
                content_type=ContentType.objects.get_for_model(Product),
                object_id=self.get_object().id
            ).exists()
        return context

    def post(self, request, *args, **kwargs):
        product = self.get_object()
        if not request.user.is_authenticated:
            return redirect('users:login')

        existing_review = Review.objects.filter(product=product, user=request.user).first()

        if existing_review:
            form = ReviewForm(request.POST, instance=existing_review)
        else:
            form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.user = request.user
            review.save()
            product.update_rating()
            return redirect(product.get_absolute_url())

        context = self.get_context_data()
        context['review_form'] = form
        return self.render_to_response(context)


class TrackProductView(LoginRequiredMixin, View):
    def get(self, request, slug):
        product = get_object_or_404(Product, slug=slug)
        content_type = ContentType.objects.get_for_model(Product)
        tracked_product = TrackedProduct.objects.filter(
            user_profile=request.user.userprofile,
            content_type=content_type,
            object_id=product.id
        ).first()

        if tracked_product:
            tracked_product.delete()
        else:
            TrackedProduct.objects.create(
                user_profile=request.user.userprofile,
                content_type=content_type,
                object_id=product.id
            )

        return HttpResponseRedirect(request.META.get('HTTP_REFERER', product.get_absolute_url()))
    

portfolio_site/templates/shop/base.html
<!DOCTYPE html>
<html lang="uk">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Магазин вінілових платівок та аксесуарів">
    <title>{% block title %}Магазин вінілових платівок{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href="{% url 'shop:index' %}">Vinyl Store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:index' %}">Головна</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'shop:product_list' %}">Каталог</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blog:posts' %}">Блог</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'cart:cart' %}">Кошик</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:profile' %}">Профіль</a>
                            </li>
                            <li class="nav-item">
                                <form action="{% url 'users:logout' %}" method="post" class="d-inline">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-secondary">Вийти</button>
                                </form>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:login' %}">Увійти</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:register' %}">Зареєструватися</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="footer">
        <div class="container text-center">
            <p>© 2025 Магазин вінілу. Всі права захищено.</p>
            <p><a href="{% url 'shop:index' %}">Головна</a> | <a href="{% url 'shop:product_list' %}">Каталог</a> | <a href="{% url 'blog:posts' %}">Блог</a></p>
        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('.select2').select2({
                placeholder: function() {
                    return $(this).data('placeholder');
                },
                allowClear: true,
                width: '100%'
            });

            // Динамічна висота для множинного вибору
            function adjustSelect2Height(select) {
                var $container = $(select).next('.select2-container').find('.select2-selection--multiple');
                $container.css('height', 'auto');
                var height = $container[0].scrollHeight;
                $container.css('min-height', height + 'px');
            }

            $('.select2').each(function() {
                if ($(this).prop('multiple')) {
                    adjustSelect2Height(this);
                }
            });

            $('.select2').on('select2:select select2:unselect change', function() {
                if ($(this).prop('multiple')) {
                    adjustSelect2Height(this);
                }
            });
        });
    </script>
</body>
</html>

portfolio_site/templates/shop/index.html
{% extends 'shop/base.html' %}
{% load static thumbnail %}
{% block content %}
<div class="index-section">
    <h1 class="mb-4 text-center">Вітаємо в магазині вінілових платівок!</h1>

    <section class="index-section">
        <h2 class="text-center">Новинки вінілу</h2>
        <div class="row">
            {% for product in new_vinyl %}
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="card h-100">
                        {% if product.image %}
                            <a href="{{ product.get_absolute_url }}"><img src="{% thumbnail product.image 'small' %}" alt="{{ product.name }}" class="card-img-top"></a>
                        {% else %}
                            <a href="{{ product.get_absolute_url }}"><img src="{% get_static_prefix %}images/placeholder.jpg" alt="No Image" class="card-img-top"></a>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title" style="color: red;">НОВИНКА!</h5>
                            <h5 class="card-title"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
                            <p class="card-text">Ціна: {{ product.get_discounted_price }} грн</p>
                            <p class="card-text">Виконавець: <a href="{% url 'shop:product_list' %}?artist={{ product.artist.id }}">{{ product.artist }}</a></p>
                            <a href="{% url 'cart:add_to_cart' product_id=product.id %}" class="btn btn-primary btn-sm">Додати в кошик</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="col-12 text-center">
                <a href="{% url 'shop:product_list' %}?is_new=true" class="btn btn-primary">Переглянути всі новинки</a>
            </div>
        </div>
    </section>

    <section class="index-section">
        <h2 class="text-center" >Знижки на вініл</h2>
        <div class="row">
            {% for product in discounted_vinyl %}
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="card h-100">
                        {% if product.image %}
                            <a href="{{ product.get_absolute_url }}"><img src="{% thumbnail product.image 'small' %}" alt="{{ product.name }}" class="card-img-top"></a>
                        {% else %}
                            <a href="{{ product.get_absolute_url }}"><img src="{% get_static_prefix %}images/placeholder.jpg" alt="No Image" class="card-img-top"></a>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
                            <p class="card-text">Ціна: <del>{{ product.price }}</del> <b style="color: #F97316;">{{ product.get_discounted_price }} грн</b></p>
                            <p class="card-text">Виконавець: <a href="{% url 'shop:product_list' %}?artist={{ product.artist.id }}">{{ product.artist }}</a></p>
                            <a href="{% url 'cart:add_to_cart' product_id=product.id %}" class="btn btn-primary btn-sm">Додати в кошик</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="col-12 text-center">
                <a href="{% url 'shop:product_list' %}?has_discount=true" class="btn btn-primary">Переглянути всі знижки</a>
            </div>
        </div>
    </section>

    <section class="index-section">
        <h2 class="text-center" >Знижки на продукти</h2>
        <div class="row">
            {% for product in discounted_products %}
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="card h-100">
                        {% if product.image %}
                            <a href="{{ product.get_absolute_url }}"><img src="{% thumbnail product.image 'small' %}" alt="{{ product.name }}" class="card-img-top"></a>
                        {% else %}
                            <a href="{{ product.get_absolute_url }}"><img src="{% get_static_prefix %}images/placeholder.jpg" alt="No Image" class="card-img-top"></a>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
                            <p class="card-text">Ціна: <del>{{ product.price }}</del> <b style="color: #F97316;">{{ product.get_discounted_price }} грн</b></p>
                            <a href="{% url 'cart:add_to_cart' product_id=product.id %}" class="btn btn-primary btn-sm">Додати в кошик</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="col-12 text-center">
                <a href="{% url 'shop:product_list' %}?has_discount=true" class="btn btn-primary">Переглянути всі знижки</a>
            </div>
        </div>
    </section>

    <section class="index-section">
        <h2 class="text-center" >Нові продукти</h2>
        <div class="row">
            {% for product in new_products %}
                <div class="col-lg-3 col-md-4 col-sm-6 mb-4">
                    <div class="card h-100">
                        {% if product.image %}
                            <a href="{{ product.get_absolute_url }}"><img src="{% thumbnail product.image 'small' %}" alt="{{ product.name }}" class="card-img-top"></a>
                        {% else %}
                            <a href="{{ product.get_absolute_url }}"><img src="{% get_static_prefix %}images/placeholder.jpg" alt="No Image" class="card-img-top"></a>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h5>
                            <p class="card-text">Ціна: {{ product.get_discounted_price }} грн</p>
                            <a href="{% url 'cart:add_to_cart' product_id=product.id %}" class="btn btn-primary btn-sm">Додати в кошик</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <div class="col-12 text-center">
                <a href="{% url 'shop:product_list' %}?is_new=true" class="btn btn-primary">Переглянути всі новинки</a>
            </div>
        </div>
    </section>
</div>
{% endblock %}

portfolio_site/templates/shop/product_detail.html
{% extends 'shop/base.html' %}
{% load static thumbnail %}
{% block content %}
<div class="product-detail">
    <div class="row">
        <div class="col-md-4">
            {% if product.image %}
                <img src="{% thumbnail product.image 'detail' %}" alt="{{ product.name }}" class="fluid-thumbnail">
            {% else %}
                <img src="{% get_static_prefix %}images/placeholder.jpg" alt="No Image" class="img-fluid">
            {% endif %}
        </div>
        <div class="col-md-8">
            <h1>{{ product.name }}</h1>
            <p><a href="{% url 'shop:product_list' %}?category={{ product.category.id }}">{{ product.category.name }}</a></p>
            <p>{{ product.description }}</p>
            {% if product.get_discounted_price == product.price %}
                <p>Ціна: {{ product.get_discounted_price }} грн</p>
            {% else %}
                <p>Ціна: <del>{{ product.price }}</del> <b style="color: #F97316;">{{ product.get_discounted_price }} грн (ЗНИЖКА -{{ product.discount }}%)</b></p>
            {% endif %}
            <p>Виробник: <a href="{% url 'shop:product_list' %}?manufacturer={{ product.manufacturer.id }}">{{ product.manufacturer }}</a></p>
            <p>Наявність: {% if product.is_available and product.quantity > 0 %}В наявності ({{ product.quantity }} шт.){% else %}Немає в наявності{% endif %}</p>
            <p>Середній рейтинг: {{ product.rating }}</p>
            {% if product.category.slug == 'vinyl-records' %}
                <p>Виконавець: <a href="{% url 'shop:product_list' %}?artist={{ product.artist.id }}">{{ product.artist }}</a></p>
                <p>Рік випуску: {{ product.release_year }}</p>
                <p>Жанр: {% for genre in product.genre.all %}<a href="{% url 'shop:product_list' %}?genre={{ product.genre.id }}">{{ genre }} </a>{% endfor %}</p>
            {% endif %}
            <div class="mt-3">
                {% if user.is_authenticated %}
                    {% if is_tracked %}
                        <a href="{% url 'shop:track_product' product.slug %}" class="button">Припинити відстежування</a>
                    {% else %}
                        <a href="{% url 'shop:track_product' product.slug %}" class="button">Відстежувати</a>
                    {% endif %}
                {% else %}
                    <a href="{% url 'users:login' %}" class="button">Увійдіть, щоб відстежувати</a>
                {% endif %}
                <a href="{% url 'cart:add_to_cart' product_id=product.id %}" class="button">Додати в кошик</a>
            </div>
        </div>
    </div>

    <hr class="my-5">

    <h3>Відгуки</h3>
    {% if user.is_authenticated %}
        <h4 class="mt-4">{{ existing_review|yesno:"Редагувати відгук,Додати відгук" }}</h4>
        <form method="post" class="card p-4">
            {% csrf_token %}
            {{ review_form.as_p }}
            <button type="submit" class="btn btn-primary">{{ existing_review|yesno:"Зберегти зміни,Надіслати" }}</button>
        </form>
    {% else %}
        <p><a href="{% url 'users:login' %}">Увійдіть</a>, щоб залишити відгук.</p>
    {% endif %}
    {% if product.reviews.exists %}
        {% for review in page_obj %}
            <div class="card mb-3">
                <div class="card-body">
                    <p class="card-text">{{ review.comment }}</p>
                    <p class="card-text">Оцінка: {{ review.rating }}/5</p>
                    <p class="card-text text-muted">Автор: <a href="{% url 'users:profile' %}?user_id={{ review.user.id }}">{{ review.user.username }}</a> | {{ review.created_at|date:"d.m.Y H:i" }}</p>
                </div>
            </div>
        {% endfor %}
        {% if page_obj.has_other_pages %}
            <nav aria-label="Page navigation">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Попередня</a>
                        </li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                        <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                            <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                        </li>
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Наступна</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    {% else %}
        <p>Відгуки відсутні.</p>
    {% endif %}
</div>
{% endblock %}